stages:
  explore:
    cmd: python src\main.py -p explore  # Usar barra invertida en las rutas para Windows
    deps:
      - src\main.py  # Usar barra invertida
    outs:
      - data\processed\explored\explored_dataset.csv  # Usar barra invertida

  split_data:
    cmd: python src\main.py -p split_data  # Usar barra invertida
    deps:
      - src\main.py  # Usar barra invertida
      - data\processed\explored\explored_dataset.csv  # Usar barra invertida
    outs:
      - data\processed\split\xtrain.csv  # Usar barra invertida
      - data\processed\split\ytrain.csv  # Usar barra invertida
      - data\processed\split\xval.csv  # Usar barra invertida
      - data\processed\split\yval.csv  # Usar barra invertida
      - data\processed\split\xtest.csv  # Usar barra invertida
      - data\processed\split\ytest.csv  # Usar barra invertida

  transform:
    cmd: python src\main.py -p transform  # Usar barra invertida
    deps:
      - src\main.py  # Usar barra invertida
      - data\processed\split\xtrain.csv  # Usar barra invertida
      - data\processed\split\ytrain.csv  # Usar barra invertida
      - data\processed\split\xval.csv  # Usar barra invertida
      - data\processed\split\yval.csv  # Usar barra invertida
      - data\processed\split\xtest.csv  # Usar barra invertida
      - data\processed\split\ytest.csv  # Usar barra invertida
    outs:
      - data\processed\transformed\xtrainT.csv  # Usar barra invertida
      - data\processed\transformed\ytrainT.csv  # Usar barra invertida
      - data\processed\transformed\xvalT.csv  # Usar barra invertida
      - data\processed\transformed\yvalT.csv  # Usar barra invertida
      - data\processed\transformed\xtestT.csv  # Usar barra invertida
      - data\processed\transformed\ytestT.csv  # Usar barra invertida

  train:
    cmd: python src\main.py -p train  # Usar barra invertida
    deps:
      - src\main.py  # Usar barra invertida
      - data\processed\transformed\xtrainT.csv  # Usar barra invertida
      - data\processed\transformed\ytrainT.csv  # Usar barra invertida

  evaluate:
    cmd: python src\main.py -p evaluate  # Usar barra invertida
    deps:
      - src\main.py  # Usar barra invertida
      - models\model.joblib  # Usar barra invertida
    outs:
      - models\metrics.json  # Usar barra invertida